name = "futurejd-landing"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "."

[env.production]
name = "futurejd-landing-prod"

[env.staging]
name = "futurejd-landing-staging" 